import React from 'react';
import PropTypes from 'prop-types';

import Head from 'next/head'
// import { makeStyles } from '@mui/styles';
import { ThemeProvider } from '@mui/material/styles';
// import { makeStyles  } from '@mui/material/styles';
import { makeStyles } from '@mui/styles';

import Selection from './Selection';

import theme from '../../theme';
import landingStyles from '../../assets/jss/landingStyles';
import { Box } from '@mui/system';
import { Paper, Typography, Grid } from '@mui/material';


const useStyles = makeStyles(landingStyles(theme))

const Landing = props => {
    const classes = useStyles()

    return (
        <ThemeProvider theme={theme}>
            <div className={classes.layout}>
                {/* <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head> */}
                <Box >
                    <Paper className={classes.logo}>
                        <Typography variant='h2' component='h2'>Kwik<span>Solutions</span></Typography>
                    </Paper>
                </Box>
                {/* <Box className={classes.mainText}>
                    <Typography variant='h1' component='h1' display="block">
                        Beautifully designed products 
                        <span> Intelligently engineered solutions </span>
                    </Typography>
                </Box> */}
                {/* <Grid container
                    alignItems="stretch"
                    justifyContent='center'
                    // alignItems="flex-start" 
                    spacing={0}>
                    <Grid item xs={12} sm={12} md={8} className={classes.gridItem}> */}
                    <Box className={classes.mainContainer}>
                        <Box className={classes.mainContent}>
                            <Box className={classes.mainText}>
                                <Typography variant='h1' component='h1' display="block">
                                    <strong>Beautifully</strong> designed products
                                    <span> <strong>Intelligently</strong> engineered solutions </span>
                                </Typography>
                            </Box>
                            <Box className={classes.optionsLayout}>
                                <Typography variant='body1' component='p'>what do you want</Typography>
                                <Selection />
                            </Box>
                        </Box>
                        </Box>
                    {/* </Grid> */}
                    {/* <Grid item xs={12} sm={12} md={4} className={classes.gridItem}> */}
                        {/* <Box className={classes.imageBox}> */}
                            {/* <img src='maximalfocus.jpg' alt='' className={classes.image} /> */}

                        {/* </Box> */}
                    {/* </Grid> */}
                {/* </Grid> */}
            </div>
        </ThemeProvider >
    );
};

Landing.propTypes = {

};

export default Landing;